export 'package:cinemapedia/presentation/providers/cast/cast_by_movieprovider.dart';
export 'movies/movies_providers.dart';
export 'movies/movies_repository_provider.dart';
export 'movies/movies_slideshow_provider.dart';
export 'movies/initial_loading_provider.dart';
export 'movies/movie_into_provider.dart';
export 'cast/cast_repository_provider.dart';
export 'theme/theme_provider.dart';
export 'searchDelegate/search_provider.dart';
